# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (6)
# #########################################################################

class AgentResponse(BaseModel):
    tools: typing.Optional[typing.Union["QuandraticSolver", "QuadraticDerivative", "QuadraticEvaluator", "MessageToUser"]] = None

class MessageToUser(BaseModel):
    type: typing.Optional[str] = None
    response: typing.Optional[str] = None
    task_status: typing.Optional[types.TaskStatus] = None

class QuadraticDerivative(BaseModel):
    type: typing.Optional[str] = None
    equation: typing.Optional[str] = None

class QuadraticEvaluator(BaseModel):
    type: typing.Optional[str] = None
    equation: typing.Optional[str] = None
    x_value: typing.Optional[str] = None

class QuandraticSolver(BaseModel):
    type: typing.Optional[str] = None
    equation: typing.Optional[str] = None

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
