# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AgentResponse": types.AgentResponse,
    "stream_types.AgentResponse": stream_types.AgentResponse,

    "types.MessageToUser": types.MessageToUser,
    "stream_types.MessageToUser": stream_types.MessageToUser,

    "types.QuadraticDerivative": types.QuadraticDerivative,
    "stream_types.QuadraticDerivative": stream_types.QuadraticDerivative,

    "types.QuadraticEvaluator": types.QuadraticEvaluator,
    "stream_types.QuadraticEvaluator": stream_types.QuadraticEvaluator,

    "types.QuandraticSolver": types.QuandraticSolver,
    "stream_types.QuandraticSolver": stream_types.QuandraticSolver,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,


    "types.TaskStatus": types.TaskStatus,

}